services:
  churn-app:

    # ваш код здесь: поле с указанием .env-файла
    # ваш код здесь: путь к файлу с переменными окружения

    #build:
    # ваш код здесь: с помощью чего собираем образ?

    # ваш код здесь: поле с указанием перенаправления портов
    # ваш код здесь: перенаправляем порты; укажите их числами.
    env_file:
      - ./.env

    # собираем образ помощью Dockerfile
    build:
      dockerfile: Dockerfile

    # перенаправляем порты
    # используем переменные из .env файла
    ports:
      - "${APP_VM_PORT}:${APP_DOCKER_PORT}" #4601:8081
    volumes:
      # тип тома 
      - type: bind
        # директория на ВМ
        source: ./models
        # директория в контейнере
        target: /churn_app/models
